"""AIra-v2 event-triggered language substrate primitives."""

from .babysit import (
    BabysitRecord,
    VerifierObservation,
    read_babysit_dataset,
    write_babysit_dataset,
)
from .bridge import BridgedShelfPrediction, ByteBPEBridge
from .calibration import ReliabilityThreshold, calibrate_reliability_threshold
from .cascade import (
    AIraCascade,
    ByteEventConfig,
    ByteEventGenerationResult,
    CognitiveCascadeResult,
    generate_byte_events,
    utf8_allowed_next_bytes,
)
from .event_core import (
    AttentionByteEventLM,
    ByteEventLM,
    ConvByteEventLM,
    EventContextLM,
    MultiByteEventLM,
    MultiByteEventLoss,
    MultiByteEventOutput,
    multi_byte_event_loss,
)
from .event_data import EventDatasetWriter, EventShardInfo, read_event_shards
from .events import (
    EventKind,
    EventPackingMetrics,
    EventTrainingBatch,
    PackedEvent,
    PackedEventStream,
    SourceCopyIndex,
    build_event_training_batch,
    pack_event_stream,
)
from .foundry import (
    ContrastiveExample,
    CurriculumRecord,
    FailureFingerprint,
    SkillPatch,
    TeacherCluster,
    TeacherPacket,
    build_teacher_packet,
    compile_curriculum,
    fingerprint_babysit_record,
    mentor_skill_patches_v1,
    write_curriculum_dataset,
    write_skill_patches,
    write_teacher_packet,
)
from .local_runtime import LocalDonorRuntime
from .memory import (
    BoundedAssociativeMemory,
    EpisodicFactStore,
    MemoryHit,
    StructuredKeyEncoder,
)
from .mixture import normalized_shelf_neural_mixture, shelf_distribution
from .on_policy import (
    OnPolicyTopKRecord,
    collect_on_policy_records,
    read_on_policy_dataset,
    records_to_teacher_topk,
    write_on_policy_dataset,
)
from .one import (
    AIraBabysitJournal,
    AIraMode,
    AIraOne,
    AIraOneResponse,
    AIraOneStats,
    ExactDecision,
    ExactRouter,
)
from .pc_alm import (
    backprop_gradients,
    gradient_cosine,
    local_augmented_gradients,
    minimum_layer_cosine,
)
from .provider import OpenAIChatProvider, ProviderError, ProviderResponse
from .residual import (
    ResidualPositionSample,
    importance_sampled_residual_loss,
    residual_training_weights,
    sample_residual_positions,
)
from .state_patcher import (
    RecurrentStatePatcher,
    StatePatchLoss,
    StatePatchOutput,
    state_patch_loss,
)
from .synthetic import (
    SyntheticMessage,
    SyntheticRecord,
    generate_aira_mentor_records,
    validate_synthetic_record,
)
from .trigger import (
    CompactShelfLevel,
    ShelfEvaluation,
    ShelfPrediction,
    ShelfRoutes,
    build_compact_shelf,
    evaluate_hierarchical_shelf,
    load_compact_shelf,
    lookup_compact_level,
    predict_shelf_next,
    route_hierarchical_shelf,
    save_compact_shelf,
)
from .verification import synthetic_generation_components, verify_synthetic_generation

__all__ = [
    "AIraBabysitJournal",
    "AIraCascade",
    "AIraMode",
    "AIraOne",
    "AIraOneResponse",
    "AIraOneStats",
    "AttentionByteEventLM",
    "BabysitRecord",
    "BoundedAssociativeMemory",
    "BridgedShelfPrediction",
    "ByteBPEBridge",
    "ByteEventConfig",
    "ByteEventGenerationResult",
    "ByteEventLM",
    "CognitiveCascadeResult",
    "CompactShelfLevel",
    "ContrastiveExample",
    "ConvByteEventLM",
    "CurriculumRecord",
    "EpisodicFactStore",
    "EventContextLM",
    "EventDatasetWriter",
    "EventKind",
    "EventPackingMetrics",
    "EventShardInfo",
    "EventTrainingBatch",
    "ExactDecision",
    "ExactRouter",
    "FailureFingerprint",
    "LocalDonorRuntime",
    "MemoryHit",
    "MultiByteEventLM",
    "MultiByteEventLoss",
    "MultiByteEventOutput",
    "OnPolicyTopKRecord",
    "OpenAIChatProvider",
    "PackedEvent",
    "PackedEventStream",
    "ProviderError",
    "ProviderResponse",
    "RecurrentStatePatcher",
    "ReliabilityThreshold",
    "ResidualPositionSample",
    "ShelfEvaluation",
    "ShelfPrediction",
    "ShelfRoutes",
    "SkillPatch",
    "SourceCopyIndex",
    "StatePatchLoss",
    "StatePatchOutput",
    "StructuredKeyEncoder",
    "SyntheticMessage",
    "SyntheticRecord",
    "TeacherCluster",
    "TeacherPacket",
    "VerifierObservation",
    "backprop_gradients",
    "build_compact_shelf",
    "build_event_training_batch",
    "build_teacher_packet",
    "calibrate_reliability_threshold",
    "collect_on_policy_records",
    "compile_curriculum",
    "evaluate_hierarchical_shelf",
    "fingerprint_babysit_record",
    "generate_aira_mentor_records",
    "generate_byte_events",
    "gradient_cosine",
    "importance_sampled_residual_loss",
    "load_compact_shelf",
    "local_augmented_gradients",
    "lookup_compact_level",
    "mentor_skill_patches_v1",
    "minimum_layer_cosine",
    "multi_byte_event_loss",
    "normalized_shelf_neural_mixture",
    "pack_event_stream",
    "predict_shelf_next",
    "read_babysit_dataset",
    "read_event_shards",
    "read_on_policy_dataset",
    "records_to_teacher_topk",
    "residual_training_weights",
    "route_hierarchical_shelf",
    "sample_residual_positions",
    "save_compact_shelf",
    "shelf_distribution",
    "state_patch_loss",
    "synthetic_generation_components",
    "utf8_allowed_next_bytes",
    "validate_synthetic_record",
    "verify_synthetic_generation",
    "write_babysit_dataset",
    "write_curriculum_dataset",
    "write_on_policy_dataset",
    "write_skill_patches",
    "write_teacher_packet",
]
