"""AIra-v2 event-triggered language substrate primitives."""

from .babysit import (
    BabysitRecord,
    VerifierObservation,
    read_babysit_dataset,
    write_babysit_dataset,
)
from .bridge import BridgedShelfPrediction, ByteBPEBridge
from .calibration import ReliabilityThreshold, calibrate_reliability_threshold
from .cascade import (
    AIraCascade,
    ByteEventConfig,
    ByteEventGenerationResult,
    CognitiveCascadeResult,
    generate_byte_events,
    utf8_allowed_next_bytes,
)
from .event_core import (
    AttentionByteEventLM,
    ByteEventLM,
    ConvByteEventLM,
    EventContextLM,
    MultiByteEventLM,
    MultiByteEventLoss,
    MultiByteEventOutput,
    multi_byte_event_loss,
)
from .event_data import EventDatasetWriter, EventShardInfo, read_event_shards
from .events import (
    EventKind,
    EventPackingMetrics,
    EventTrainingBatch,
    PackedEvent,
    PackedEventStream,
    SourceCopyIndex,
    build_event_training_batch,
    pack_event_stream,
)
from .memory import (
    BoundedAssociativeMemory,
    EpisodicFactStore,
    MemoryHit,
    StructuredKeyEncoder,
)
from .mixture import normalized_shelf_neural_mixture, shelf_distribution
from .on_policy import (
    OnPolicyTopKRecord,
    collect_on_policy_records,
    read_on_policy_dataset,
    records_to_teacher_topk,
    write_on_policy_dataset,
)
from .pc_alm import (
    backprop_gradients,
    gradient_cosine,
    local_augmented_gradients,
    minimum_layer_cosine,
)
from .residual import (
    ResidualPositionSample,
    importance_sampled_residual_loss,
    residual_training_weights,
    sample_residual_positions,
)
from .trigger import (
    CompactShelfLevel,
    ShelfEvaluation,
    ShelfPrediction,
    ShelfRoutes,
    build_compact_shelf,
    evaluate_hierarchical_shelf,
    load_compact_shelf,
    lookup_compact_level,
    predict_shelf_next,
    route_hierarchical_shelf,
    save_compact_shelf,
)

__all__ = [
    "AIraCascade",
    "AttentionByteEventLM",
    "BabysitRecord",
    "BoundedAssociativeMemory",
    "BridgedShelfPrediction",
    "ByteBPEBridge",
    "ByteEventConfig",
    "ByteEventGenerationResult",
    "ByteEventLM",
    "CognitiveCascadeResult",
    "CompactShelfLevel",
    "ConvByteEventLM",
    "EpisodicFactStore",
    "EventContextLM",
    "EventDatasetWriter",
    "EventKind",
    "EventPackingMetrics",
    "EventShardInfo",
    "EventTrainingBatch",
    "MemoryHit",
    "MultiByteEventLM",
    "MultiByteEventLoss",
    "MultiByteEventOutput",
    "OnPolicyTopKRecord",
    "PackedEvent",
    "PackedEventStream",
    "ReliabilityThreshold",
    "ResidualPositionSample",
    "ShelfEvaluation",
    "ShelfPrediction",
    "ShelfRoutes",
    "SourceCopyIndex",
    "StructuredKeyEncoder",
    "VerifierObservation",
    "backprop_gradients",
    "build_compact_shelf",
    "build_event_training_batch",
    "calibrate_reliability_threshold",
    "collect_on_policy_records",
    "evaluate_hierarchical_shelf",
    "generate_byte_events",
    "gradient_cosine",
    "importance_sampled_residual_loss",
    "load_compact_shelf",
    "local_augmented_gradients",
    "lookup_compact_level",
    "minimum_layer_cosine",
    "multi_byte_event_loss",
    "normalized_shelf_neural_mixture",
    "pack_event_stream",
    "predict_shelf_next",
    "read_babysit_dataset",
    "read_event_shards",
    "read_on_policy_dataset",
    "records_to_teacher_topk",
    "residual_training_weights",
    "route_hierarchical_shelf",
    "sample_residual_positions",
    "save_compact_shelf",
    "shelf_distribution",
    "utf8_allowed_next_bytes",
    "write_babysit_dataset",
    "write_on_policy_dataset",
]
